export const CONFIG = {
  title: "Le Havre Aixois",
  subtitle: "A serene hideaway in the heart of Aix-en-Provence",
  airbnbUrl: "https://www.airbnb.com/h/havreaixois",
  bookingUrl: "#",
  vrboUrl: "https://www.vrbo.com/4800130",
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "contact@havreaixois.com",
  contactEndpoint: process.env.NEXT_PUBLIC_CONTACT_ENDPOINT || "",
  heroImage:
    "https://images.unsplash.com/photo-1563729784474-3a5372a7f1cf?q=80&w=1600&auto=format&fit=crop",
  gallery: [
    "/photos/livingroom1.jpeg",
    "/photos/kitchen1.jpeg",
    "/photos/master-bedroom1.jpeg",
    "/photos/master-bedroom2.jpeg",
    "/photos/master-bath1.jpeg",
    "/photos/2nd-bedroom1.jpeg",
    "/photos/2nd-bedroom2.jpeg",
    "/photos/2nd-bath1.jpeg",
    "/photos/office1.jpeg",
    "/photos/office-2.jpeg",
    "/photos/terrace1.jpeg",
    "/photos/terrace2.jpeg",
    "/photos/terrace3.jpeg",
  ],
};
